WebApp/Controllers/BusquedaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Servicios;
using WebApp.DTO;
using WebApp.Experto;

using WebApp.DTOJSon;
using System.Text.RegularExpressions;
using System.Globalization;
using LibreriaClases;
using MercadoPago.DataStructures.Customer;
using LibreriaExperto.Busquedas;
using LibreriaExperto.Seguridad;
using LibreriaClases.DTO;
using NUnit.Framework.Constraints;

namespace WebApp.Controllers
{
    public class BusquedaController : Controller
    {
        ExpertoRealizarBusqueda realizarBusquedaExperto = new ExpertoRealizarBusqueda();
        BusquedaServicios bs = new BusquedaServicios();
        
        [HttpGet]
        public ActionResult Buscar() {
            try
            {
                
                (ErrorPropy error, DTOParametrosBusqueda parametrosBusqueda) respuesta = ExpertoBusquedas.ObtenerParametrosBusqueda();
                
                return View(respuesta.parametrosBusqueda);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.ErrorDetalle = ex.StackTrace;
                return View("Error");
               
            }
            
        }
        [HttpPost]
        public ActionResult Buscar(string clientAddress,string latitud,string longitud, string tipoOperacion,string tipoPropiedad,string tipoConstruccion,string moneda, string tipoPublicante,string precioDesde,string precioHasta,bool característicasEspecificas,string cantidadDormitorios, string cantidadAmbientes, string cantidadBaños, string cantidadCocheras,int radio,List<string> extras) {
            try
            {
                #region Conversiones
                double lat = Double.Parse(latitud, CultureInfo.InvariantCulture);
                double lng = Double.Parse(longitud, CultureInfo.InvariantCulture);
                int cantBaños = 0;
                int cantDormitorios = 0;
                int cantAmbientes = 0;
                int cantCocheras = 0;
                decimal precioD = 0;
                decimal precioH = 0;
                if (extras is null) { extras = new List<string>(); }
                if (!String.IsNullOrEmpty(precioDesde)) { precioD = Convert.ToDecimal(precioDesde); }
                if (!String.IsNullOrEmpty(precioHasta)) { precioH = Convert.ToDecimal(precioHasta); }
                if (!String.IsNullOrEmpty(cantidadAmbientes)) { cantAmbientes = Convert.ToInt32(cantidadAmbientes); }
                if (!String.IsNullOrEmpty(cantidadBaños)) { cantBaños = Convert.ToInt32(cantidadBaños); }
                if (!String.IsNullOrEmpty(cantidadDormitorios)) { cantDormitorios = Convert.ToInt32(cantidadDormitorios); }
                if (!String.IsNullOrEmpty(cantidadCocheras)) { cantCocheras = Convert.ToInt32(cantidadCocheras); }
                
                #endregion
                ErrorPropy error = new ErrorPropy();
                error = ValidacionParametros.ValidacionBusqueda(precioD,precioH);
                if (error.codigoError!=0) {
                    ViewBag.Error = error.descripcionError;
                    ModelState.AddModelError("", error.descripcionError);
                    (ErrorPropy error, DTOParametrosBusqueda parametrosBusqueda) res = ExpertoBusquedas.ObtenerParametrosBusqueda();
                    
                    return View(res.parametrosBusqueda);
                }
                LibreriaClases.DTO.DTOFiltrosBusqueda parametrosBusqueda = new LibreriaClases.DTO.DTOFiltrosBusqueda();
                parametrosBusqueda.ubicacion = clientAddress;
                parametrosBusqueda.tipoPublicacion = tipoOperacion;
                parametrosBusqueda.tipoPropiedad = tipoPropiedad;
                parametrosBusqueda.tipoConstruccion = tipoConstruccion;
                parametrosBusqueda.tipoPublicante = tipoPublicante;
                parametrosBusqueda.precioDesde = precioD;
                parametrosBusqueda.precioHasta = precioH;
                parametrosBusqueda.característicasEspecificasHabilitadas = característicasEspecificas;
                parametrosBusqueda.cantidadCocheras = cantCocheras;
                parametrosBusqueda.cantidadBaños = cantBaños;
                parametrosBusqueda.cantidadDormitorios = cantDormitorios;
                parametrosBusqueda.cantidadAmbientes = cantAmbientes;
                parametrosBusqueda.latitud = lat;
                parametrosBusqueda.longitud = lng;
                parametrosBusqueda.radioBusqueda = radio;
                parametrosBusqueda.extras = extras;
                parametrosBusqueda.denominacionMoneda = moneda;
                

                (ErrorPropy error, LibreriaClases.DTO.DTOContenedorResultadosBusqueda resultadosBusqueda) respuesta = ExpertoBusquedas.Buscar(parametrosBusqueda);
                if (respuesta.error.codigoError==-1) {
                    ViewBag.Error = respuesta.error.descripcionError;
                    ModelState.AddModelError("",respuesta.error.descripcionError);
                    (ErrorPropy error, DTOParametrosBusqueda parametrosBusqueda) respuesta2 = ExpertoBusquedas.ObtenerParametrosBusqueda();
                    
                    return View(respuesta2.parametrosBusqueda);
                }
                
                return View("ResultadosBusqueda",respuesta.resultadosBusqueda);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.ErrorDetalle = ex.StackTrace;
                return View("Error");
               
            }
        }
        
        // GET: Busqueda
        public ActionResult Index()
        {
            try
            {
                return View(realizarBusquedaExperto.PrepararFiltrosParaBusqueda());
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Error", new { codError = ex.HResult, descripcionError = ex.Message });
                
            }
           

            
            
        }
        [HttpPost]
        public ActionResult Index(string clientAddress, string tipoPropiedad, string tipoOperacion, string tipoConstruccion, List<string> extras, String precioDesde, String precioHasta,
            string tipoMoneda, int radio, string latitud, string longitud, string SupTMax, string SupTMin, int cantidadBaños = -1, 
            int cantidadDormitorios = -1, int cantidadCocheras = -1, int antiguedad = -1, int cantidadPlantas = -1, int cantidadAmbientes =- 1) 
        {
            try
            {

                ValidacionErroresServicios.PrevenirErroresNull(ref precioDesde, ref precioHasta, ref SupTMax, ref SupTMin, ref clientAddress, ref radio);
                
                //Convierto latitud y longitud en float
                double lat = Double.Parse(latitud, CultureInfo.InvariantCulture);
                double lng = Double.Parse(longitud, CultureInfo.InvariantCulture);

                //saco el formato numérico al precioPropiedad
                string patron = @"[^\w]";
                Regex regex = new Regex(patron);
                string PRECIOdesde = regex.Replace(precioDesde, "");
                string PRECIOhasta = regex.Replace(precioHasta, "");
                string SupTerrenoMax = regex.Replace(SupTMax, "");
                string SupTerrenoMin = regex.Replace(SupTMin, "");
                string rutaRelativa = Server.MapPath("~");



                DTOValidarParametrosFiltrosBusqueda dtoValidacion = new DTOValidarParametrosFiltrosBusqueda();
                dtoValidacion.precioDesde = Convert.ToDecimal(PRECIOdesde);
                dtoValidacion.precioHasta = Convert.ToDecimal(PRECIOhasta);
                dtoValidacion.SuperficieTerrenoMax = Convert.ToInt32(SupTerrenoMax);
                dtoValidacion.SuperficieTerrenoMin = Convert.ToInt32(SupTerrenoMin);
                DTOError errores = ValidacionErroresServicios.ValidarEnvioParametrosFiltroBusqueda(dtoValidacion);

                if (errores.codigoError != 0)
                {

                    foreach (var error in errores.descripcionError)
                    {
                        ModelState.AddModelError("", error);
                    }
                    return View(realizarBusquedaExperto.PrepararFiltrosParaBusqueda());
                }
                else
                {
                    DTOBusqueda dto = new DTOBusqueda();
                    if (clientAddress == "")
                    {
                        dto.areaAdministrativaNivel1 = "-1";
                        dto.areaAdministrativaNivel2 = "-1";
                        dto.pais = "-1";
                    }
                    else
                    {
                        string query = "https://maps.googleapis.com/maps/api/geocode/json?address=" + clientAddress + "&key=AIzaSyAYs2ZkTPnJsgVZSiiGjCMw9C81tu7JViw";
                        DTORootObjectAddress rootObjAddress = APIGoogleMapsServicios.SolicitarUbicacionCompleta(query);
                        if (rootObjAddress.status == "OK")
                        {
                            for (int i = 0; i < rootObjAddress.results[0].address_components.Count; i++)
                            {
                                switch (rootObjAddress.results[0].address_components[i].types[0])
                                {
                                    case "administrative_area_level_2":
                                        dto.areaAdministrativaNivel2 = rootObjAddress.results[0].address_components[i].long_name;
                                        break;
                                    case "administrative_area_level_1":
                                        dto.areaAdministrativaNivel1 = rootObjAddress.results[0].address_components[i].long_name;
                                        break;
                                    case "country":

WebApp/Views/Busqueda/CargarBusquedaEspecifica.cshtml
@model WebApp.DTO.DTOTodosResultadosBusqueda

@{
    ViewBag.Title = "CargarBusquedaGenerica";

}

<h2>Resultado de Búsqueda</h2>
@foreach (var item in Model.ListaDtoResultadoPublicacion)
{
    <div class="panel panel-info">
        <div class="panel-heading">@item.tipoPropiedad</div>
        <div class="panel-body">
            <div class="row">
                <center>
                    <div class="col-md-4">
                        <img src='@Url.Action("VisualizarImagen", "Publicacion", new { publicacionId = @item.publicacionId })' class="img-responsive" alt="" height=200 width=300 />
                    </div>
                    <div class="col-md-4">
                        <div class="row">
                            <label class="control-label">Tipo de Propiedad:</label>@item.tipoPropiedad
                        </div>
                        <div class="row">
                            <label class="control-label">Tipo de Operación:</label>@item.tipoOperacion
                        </div>
                        <div class="row">
                            <label class="control-label">Dirección:</label>@item.direccionPropiedad
                        </div>
                        <div class="row">
                            <label class="control-label">País:</label>@item.pais
                        </div>
                        <div class="row">
                            <label class="control-label">Provincia:</label>@item.provincia
                        </div>
                        <div class="row">
                            <label class="control-label">Ciudad:</label>@item.ciudad
                        </div>
                        <div class="row">
                            <label class="control-label">Precio:$</label>@item.precioPropiedad
                        </div>
                        <div class="row">
                            <label class="control-label">Fecha de Publicacíón:</label>@item.fechaInicioPublicacion
                        </div>
                    </div>
                    <div class="col-md-4">
                        @Html.ActionLink("Ver datos publicante", "Index", "SolicitarContactoPublicante", new { publicacionId = item.publicacionId }, new { @class = "btn btn-lg btn-primary" });
                    </div>
                </center>

            </div>
        </div>
    </div>
}

WebApp/Views/Busqueda/CargarBusquedaGenerica.cshtml
@model WebApp.DTO.DTOTodosResultadosBusqueda

@{
    ViewBag.Title = "CargarBusquedaGenerica";
    
}

<h2>Resultado de Búsqueda</h2>
@foreach (var item in Model.ListaDtoResultadoPublicacion)
{
    <div class="panel panel-info">
        <div class="panel-heading">@item.tipoPropiedad</div>
        <div class="panel-body">
            <div class="row">
                <center>
                    <div class="col-md-4">
                        <img src='@Url.Action("VisualizarImagen","Publicacion",new {publicacionId=@item.publicacionId})' class="img-responsive" alt="" height=200 width=300 />
                    </div>
                    <div class="col-md-4">
                        <div class="row">
                            <label class="control-label">Publicacion ID:</label>@item.publicacionId
                        </div>
                        <div class="row">
                            <label class="control-label">Tipo de Propiedad:</label>@item.tipoPropiedad
                        </div>
                        <div class="row">
                            <label class="control-label">Tipo de Operación:</label>@item.tipoOperacion
                        </div>
                        <div class="row">
                            <label class="control-label">Dirección:</label>@item.direccionPropiedad
                        </div>
                        <div class="row">
                            <label class="control-label">País:</label>@item.pais
                        </div>
                        <div class="row">
                            <label class="control-label">Provincia:</label>@item.provincia
                        </div>
                        <div class="row">
                            <label class="control-label">Ciudad:</label>@item.ciudad
                        </div>
                        <div class="row">
                            <label class="control-label">Precio:$</label>@item.precioPropiedad
                        </div>
                        <div class="row">
                            <label class="control-label">Fecha de Publicacíón:</label>@item.fechaInicioPublicacion
                        </div>
                    </div>
                    <div class="col-md-4">
                        @Html.ActionLink("Ver datos publicante","Index","SolicitarContactoPublicante",new {publicacionId=item.publicacionId },new {@class="btn btn-lg btn-primary" });
                        
                    </div>
                </center>

            </div>
        </div>
    </div>
    

}

WebApp/Views/Busqueda/RealizarBusqueda.cshtml
@model WebApp.DTO.DTOTodosResultadosBusqueda

@{
    ViewBag.Title = "Resultado de búsqueda";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@section Styles{
    <link href="~/Estilos/MisEstilos.css" rel="stylesheet" />
    <style>
        /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
        #map {
            height: 500px;
            width: 1500px;
        }
        /* Optional: Makes the sample page fill the window. */

    </style>
}
<script src="~/Scripts/ValidacionesBusqueda.js"></script>

<div class="container">
    <h2 class="mt-4">Resultados de Búsqueda</h2>
    @if (Model.ListaDtoResultadoPublicacion.Count == 0)
    {
        <div class="alert alert-info" role="alert">
            <h4>Lo sentimos, no se han encontrado resultados.</h4>
        </div>

        @Html.ActionLink("Volver a buscar", "Index", "Busqueda", new { @class = "btn btn-sm btn-primary" })
    }
    else
    {

        <br />
        <div class="row">
            <div class="col-md-6">
                @Html.ActionLink("Volver a buscar", "Index", "Busqueda", new { @class = "btn btn-sm btn-primary" })
            </div>
            <div class="col-md-6">
                <form method="post" action='@Url.Action("RealizarBusqueda", "Busqueda",new {publicaciones=@ViewData["publicaciones"]})'>
                    <div class="form-group">
                        <div class="text-right">
                            <label for="selectorOrdenamiento">Ordenar por:</label>
                            <select id="selectorOrdenamiento" name="condicionOrdenamiento">
                                <option value="SoloPrecio">Sólo precio</option>
                                <option value="SoloFecha">Sólo fecha</option>
                                <option value="PrecioFecha">Precio y Fecha</option>
                            </select>
                            <input type="submit" name="Aplicar" value="Aplicar" class="btn btn-primary btn-sm" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="Contenedor">
            <div id="map" class="img-fluid">

            </div>
        </div>

        <br />


        foreach (var item in Model.ListaDtoResultadoPublicacion)
        {
            <div class="Contenedor">
                <h4>@item.tipoPropiedad</h4>
                <div class="row justify-content-center justify-content-lg-start ">
                    <div class="col-md-8">
                        <img src="@item.rutaImagenBD.First()" class="img-fluid" />
                    </div>
                    <div class="col-md-4 text-dark text-left" style="font-size: 12.5px;">
                        <ul style="list-style-type: none;">
                            <li>Tipo de Propiedad:&nbsp;<b>@item.tipoPropiedad</b></li>
                            <li>Tipo de Operación:&nbsp;<b>@item.tipoOperacion</b></li>
                            <li>Dirección:&nbsp;<b>@item.direccionPropiedad @item.nroCalle,@item.ciudad,@item.provincia,@item.pais</b></li>
                            <li>Precio: $&nbsp;<b>@item.precioPropiedad&nbsp;@item.tipoMoneda</b></li>
                            <li>Fecha de Publicacíón:&nbsp;<b>@item.fechaInicioPublicacion</b></li>
                            <hr style="border-color:red; margin:11.5px;margin-left:0px;" />
                            <li>@Html.ActionLink("Conocer datos inmueble", "Index", "SolicitarDatosInmueble", new { publicacionId = item.publicacionId }, new { @class = "btn btn-sm btn-primary" })</li>
                            <hr style="border-color:red; margin:11.5px;margin-left:0px;" />
                            <li>@Html.ActionLink("Ver datos publicante", "Index", "SolicitarContactoPublicante", new { publicacionId = item.publicacionId }, new { @class = "btn btn-sm btn-secondary" })</li>
                        </ul>
                    </div>

                </div>
            </div>
        }


    }
</div>


@section scripts{
    <script>
        
        function initMap() {
            var modelo = @Html.Raw(Json.Encode(Model));
            var icono;
            var infoWindows = [];
            var markers = [];
            var myLatLng = { lat: modelo.ListaDTOCoordProp[0].latitud, lng: modelo.ListaDTOCoordProp[0].longitud };
            var publicacionId;
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 12,
                center: myLatLng
            });

            for (var i = 0; i < modelo.ListaDTOCoordProp.length; i++) {
                publicacionId = modelo.ListaDTOCoordProp[i].publicacionId;
                var link = '@Html.ActionLink("Ir al inmueble","Index", "SolicitarDatosInmueble",new { publicacionId = "-1" },null)';
                link = link.replace("-1", publicacionId);
                
                infoWindows.push(contenidoInfoWindow);
                switch (modelo.ListaDTOCoordProp[i].tipoPropiedad) {
                    case "Casa":
                        icono = "/Icons/casaIcono.png";
                        break;
                    case "Departamento":
                        icono = "/Icons/departamentoIcono.png";
                        break;
                    case "Oficina":
                        icono = "/Icons/edificioIcono.png";
                        break;
                    default:
                        icono = "/Icons/casaIcono.png";
                        break;
                }
                var precio = modelo.ListaDTOCoordProp[i].precioPropiedad
                var marker = new google.maps.Marker({
                    draggable: false,
                    
                    position: { lat: modelo.ListaDTOCoordProp[i].latitud, lng: modelo.ListaDTOCoordProp[i].longitud },
                    map: map,
                    
                    title: modelo.ListaDTOCoordProp[i].tipoPropiedad + ' ' + modelo.ListaDTOCoordProp[i].ubicacion + ' ' + modelo.ListaDTOCoordProp[i].precioPropiedad,
                    icon: icono

                });
                markers.push(marker);
                var infowindow = new google.maps.InfoWindow();
                var contenidoInfoWindow = '<div id="content">' +
                    '<div id="siteNotice">' +
                    '</div>' +
                    '<h1 id="firstHeading" class="firstHeading">' + modelo.ListaDTOCoordProp[i].tipoMoneda +' ' +modelo.ListaDTOCoordProp[i].precioPropiedad + '</h1>' +
                    '<div id="bodyContent">' +
                    '<h4><b>' + modelo.ListaDTOCoordProp[i].tipoPropiedad + '</b></h4>' +
                    '<h4>' + modelo.ListaDTOCoordProp[i].ubicacion + '</h2>' +
                    '<h4> ' + link + '</h4>' +
                    '</div>' +
                    '</div>';

                
                google.maps.event.addListener(marker, 'click', (function (marker, contenidoInfoWindow, infowindow) {
                    return function () {
                        infowindow.setContent(contenidoInfoWindow);
                        infowindow.open(map, marker);
                    };
                })(marker, contenidoInfoWindow, infowindow)); 
                
            }
            
            

        }
    </script>
    
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYs2ZkTPnJsgVZSiiGjCMw9C81tu7JViw&callback=initMap">
    </script>
}

WebApp/Views/Busqueda/ResultadosBusqueda.cshtml
@model LibreriaClases.DTO.DTOContenedorResultadosBusqueda
@{
    ViewBag.Title = "ResultadosBusqueda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Styles{

    <style>
        /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
        #map {
            height: 500px;
            width: 100%;
        }
        /* Optional: Makes the sample page fill the window. */

    </style>
}
<div class="container">
    @if (Model.propiedades.Count() == 0)
    {
    <div class="alert alert-info">
        <p>No se han encontrado resultados.</p>
    </div>
        
    }
    else
    {
<div class="mt-5 mb-5">
    <h4>Resultados de búsqueda</h4>
    <p class="text-success">Se han encontrado <b>@Model.propiedades.Count()</b> resultados</p>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Visualizar en el mapa
            </button>
            <div class="collapse" id="collapseExample">
                <div class="card card-body">
                    <div id="map" class="img-fluid img-thumbnail">

                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>
        
        
        foreach (var propiedad in Model.propiedades)
        {
            <div class="card bg-light border-dark">
                <div class="card-header border-dark">
                    <h6>@propiedad.tipoPropiedad en (@propiedad.tipoPublicacion)</h6>
                </div>
                <div class="card-body bg-light">
                    <div class="row">
                        <div class="col-md-3">
                            <img src="@propiedad.imagen" class="img-fluid img-thumbnail" />
                        </div>
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col">
                                    <label>Ubicación: <b>@propiedad.ubicación</b></label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <label>Fecha de publicación: <b>@propiedad.fechaInicioPublicacion</b></label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <label>Precio: <b>(@propiedad.tipoMoneda) $@propiedad.precioPropiedad</b></label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <label>Publicante: <b>@propiedad.tipoPublicante</b></label>
                                </div>
                                
                            </div>
                        </div>
                        <div class="col-md-3 text-right">
                            @Html.ActionLink("Visitar", "VisitarPublicacion", "VisitaInmueble", new {publicacionId=propiedad.publicacionId }, new { @class = "btn btn-md btn-outline-success" })
                        </div>
                    </div>
                </div>

            </div>
            <hr />
        }

        
    }
</div>


@section scripts{
    <script>

        function initMap() {
            var modelo = @Html.Raw(Json.Encode(Model));
            var icono;
            var infoWindows = [];
            var markers = [];
            var myLatLng = { lat: modelo.pinchesGoogleMaps[0].latitud, lng: modelo.pinchesGoogleMaps[0].longitud };
            var publicacionId;
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 12,
                center: myLatLng
            });

            for (var i = 0; i < modelo.pinchesGoogleMaps.length; i++) {
                publicacionId = modelo.pinchesGoogleMaps[i].publicacionId;
                var link = '@Html.ActionLink("Ir al inmueble","VisitarPublicacion", "VisitaInmueble",new { publicacionId = "-1"},null)';
                link = link.replace("-1", publicacionId);

                infoWindows.push(contenidoInfoWindow);
                switch (modelo.pinchesGoogleMaps[i].tipoPropiedad) {
                    case "Casa":
                        icono = "/Icons/casaIcono.png";
                        break;
                    case "Departamento":
                        icono = "/Icons/departamentoIcono.png";
                        break;
                    case "Oficina":
                        icono = "/Icons/edificioIcono.png";
                        break;
                    default:
                        icono = "/Icons/casaIcono.png";
                        break;
                }
                var precio = modelo.pinchesGoogleMaps[i].precioPropiedad
                var marker = new google.maps.Marker({
                    draggable: false,

                    position: { lat: modelo.pinchesGoogleMaps[i].latitud, lng: modelo.pinchesGoogleMaps[i].longitud },
                    map: map,

                    title: modelo.pinchesGoogleMaps[i].tipoPropiedad + ' ' + modelo.pinchesGoogleMaps[i].ubicacion + ' ' + modelo.pinchesGoogleMaps[i].precioPropiedad,
                    icon: icono

                });
                markers.push(marker);
                var infowindow = new google.maps.InfoWindow();
                var contenidoInfoWindow = '<div id="content">' +
                    '<div id="siteNotice">' +
                    '</div>' +
                    '<h1 id="firstHeading" class="firstHeading">' + modelo.pinchesGoogleMaps[i].tipoMoneda + ' ' + modelo.pinchesGoogleMaps[i].precioPropiedad + '</h1>' +
                    '<div id="bodyContent">' +
                    '<h4><b>' + modelo.pinchesGoogleMaps[i].tipoPropiedad + '</b></h4>' +
                    '<h4>' + modelo.pinchesGoogleMaps[i].ubicacion + '</h2>' +
                    '<h4> ' + link + '</h4>' +
                    '</div>' +
                    '</div>';


                google.maps.event.addListener(marker, 'click', (function (marker, contenidoInfoWindow, infowindow) {
                    return function () {
                        infowindow.setContent(contenidoInfoWindow);
                        infowindow.open(map, marker);
                    };
                })(marker, contenidoInfoWindow, infowindow));

            }



        }
    </script>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYs2ZkTPnJsgVZSiiGjCMw9C81tu7JViw&callback=initMap">
    </script>
}