WebApp/Controllers/ContratarPlanController.cs
using System;
using System.Web.Mvc;
using LibreriaExperto.Seguridad;
using LibreriaClases;
using LibreriaClases.DTO;
using System.Net.Http;
using MercadoPago;
using LibreriaMercadoPago.Comunicacion_MercadoPago;
using LibreriaMercadoPago.Interface_Compra;
using LibreriaMercadoPago.Plan;
using System.Collections.Generic;
using MercadoPago.Resources;

namespace WebApp.Controllers
{
    public class ContratarPlanController : Controller
    {
        [AllowAnonymous]
        [Authorize]
        public ActionResult Index()
        {
            try
            {
                if (!ControlAcceso.Autorizacion(Session["IDUsuario"])) { return RedirectToAction("Index", "Home", null); }

                var user = Session["IDUsuario"].ToString();

                Compra<DTOPlan> compra = new ExpertoContratarPlan<DTOPlan>();

                ExpertoPlan expertoPlan = new ExpertoPlan();

                var PlanExistente = expertoPlan.YaTienePlan(user);

                var Result = compra.ObtenerPlanes_o_Credito();

                if (PlanExistente == false)
                {
                    var Compras = compra.ArmarDTOCompra(user, Result.Item2);

                    return View(Compras.Item2);
                }
                else
                {
                    return RedirectToAction("ConsultarPlan", "GestionarPlan");
                }
            }
            catch (Exception error)
            {
                ViewBag.Error = error.Message;
                return View("Error");
            }
        }
        [GETEndpoint("ContratarPlan/Notification")]
        public ActionResult Notification(string payment_id, string preference_id)//por este metodo entra la IPN de mercadopago y se reciben los QueryString
        {
            try
            {
                ExpertoNotification Notification = new ExpertoNotification();
                (DTONotification dTONotification, Preference preference, var Pago)  = Notification.ProcesarEstado(payment_id, preference_id);

                if (dTONotification.Aprobado == true)
                {
                    ExpertoPlan expertoPlan = new ExpertoPlan();
                    expertoPlan.AsignarPlan(preference,Pago);
                }
                return View("~/Views/PaymentNotification/Notification.cshtml", dTONotification);
            }
            catch (Exception error)
            {
                ViewBag.Error = error.Message;
                ViewBag.detalleError = error.StackTrace;
                return View("Error");
            }
        }
    }
}

WebApp/Views/ContratarPlan/Index.cshtml
@model LibreriaMercadoPago.DTO.DTOCompra


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/PanelControl2.cshtml";
}
<script src="https://www.mercadopago.com/v2/security.js" view="home"></script>

@if (!String.IsNullOrEmpty(ViewBag.Error))
{
    <div class="alert alert-danger">
        <button class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @Html.ValidationSummary(false)
    </div>
}


<h2 class="text-primary mt-4" style="color:purple;">Planes</h2>

<div class="container mt-4">
    <div class="row justify-content-center">

        @{
            Int32 contador = 0;
            foreach (var prefences in Model.preferences)
            {
                <div class="col-12 col-lg-3 card ml-lg-3 mt-3 Contenedor" style="background-image: linear-gradient(to bottom right,gold,white);">
                    <div class="card-header" style="background-color:transparent;">
                        <h3>@Model.dTOPlanes.ElementAt(contador).nombrePlan</h3>
                        <hr />
                        <h5>$@Model.dTOPlanes.ElementAt(contador).precioPlan @Model.dTOPlanes.ElementAt(contador).tipoMoneda.denominacionMoneda</h5>
                    </div>
                    <div class="card-body ">
                        @if (Model.dTOPlanes.ElementAt(contador).accesoEstadisticasAvanzadas == true)
                        {
                            <h6 style="font-size:13px;"><b>Vista preferencial:</b>&nbsp;Si</h6>
                        }
                        else
                        {
                            <h6 style="font-size:13px;"><b>Vista preferencial:</b>&nbsp;No</h6>
                        }
                        <h6 style="font-size:13px;"><b>Fotos por publicación:</b>&nbsp;@Model.dTOPlanes.ElementAt(contador).cantidadMaxImagenesPermitidasPorPublicacion</h6>
                        @if (Model.dTOPlanes.ElementAt(contador).permiteVideo == true)
                        {
                            <h6 style="font-size:13px;"><b>Publicar video:</b>&nbsp;Si</h6>
                        }
                        else
                        {
                            <h6 style="font-size:13px;"><b>Publicar video:</b>&nbsp;No</h6>
                        }
                        <!--<h6 style="font-size:13px;"><b>Vencimiento de créditos:</b>&nbsp;Model.dTOPlanes.ElementAt(contador).vencimientoCreditos</h6>-->
                        <h6 style="font-size:13px;"><b>Créditos:</b>&nbsp;@Model.dTOPlanes.ElementAt(contador).cantidadCreditosIniciales</h6>
                    </div>
                    <div class="card-footer">
                        <div class="row justify-content-center">
                            <form action="@Url.Action("Notification","ContratarPlan")" method="post">
                                <script src="https://www.mercadopago.com.ar/integrations/v1/web-payment-checkout.js"
                                        data-preference-id="@Html.DisplayFor( model => prefences.Id)" data-button-label="Comprar">
                                </script>
                            </form>
                        </div>
                    </div>
                </div>
                contador++;
            }
        }
    </div>
</div>